# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='date',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='caption',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='images',
            name='img',
            field=models.ImageField(upload_to='media'),
        ),
    ]
