# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20171025_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='timestamp',
            field=models.DateField(verbose_name='datetime'),
        ),
    ]
