# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('img', models.ImageField(upload_to='media')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
